[package]
name = "ckb-integration-test"
version = "0.0.1"
authors = ["keroro <keroroxx520@gmail.com>"]
edition = "2018"
homepage = "https://github.com/nervosnetwork/ckb"
repository = "https://github.com/nervosnetwork/ckb"
description = "ckb integration tests"

[dependencies]
clap = { version = "2" }
ckb-jsonrpc-types = { git = "https://github.com/nervosnetwork/ckb", rev = "603a811" }
ckb-types = { git = "https://github.com/nervosnetwork/ckb", rev = "603a811" }
ckb-logger-config = { git = "https://github.com/nervosnetwork/ckb", rev = "603a811" }
ckb-logger-service = { git = "https://github.com/nervosnetwork/ckb", rev = "603a811" }
lazy_static = "1.4.0"
log = "0.4"
ckb-testkit = { path = "../ckb-testkit" }
ckb-exec-params = { git = "https://github.com/keroro520/ckb_exec_test_script", rev = "ddf874a1ecbcc4386403eb6658abdaeb6a4a8450", package = "exec_params" }
