---
- hosts: all
  name: sync-mainnet
  gather_facts: yes
  tasks:
    - include_vars: vars/all.yml
      tags: [ always ]
    - name: Operate CKB Via Ansible-CKB
      include_role:
        name: ansible-ckb
        public: false
      tags:
        - ckb_install
        - ckb_configure
        - ckb_restart
        - ckb_start
        - ckb_stop
        - ckb_status
        - ckb_miner_restart
        - ckb_miner_start
        - ckb_miner_stop

    - name: Wait For CKB Synchronization
      block:
        - name: Wait Until CKB Reach Tip Number `{{ ckb_sync_target_number }}`
          wait_for:
            path: "{{ ckb_data_dir }}/logs/run.log"
            search_regex: "(?P<line>.* ChainService INFO ckb_chain::chain  block: {{ ckb_sync_target_number }}, .*)"
            timeout: 900   # in seconds
          register: wait_until_reach_explorer_tip
        - debug:
            msg: "{{ wait_until_reach_explorer_tip['match_groupdict']['line'] }}"
      tags:
        - wait_ckb_synchronization

    # run ckb replay from 1 to tip (based on sync db)
    - name: Run and Wait for CKB replay
      block:
        - name: Stop CKB
          become: true
          service:
            name: "{{ ckb_service }}"
            state: stopped
        - name: CKB Replay
          become: true
          shell: "{{ ckb_workspace }}/ckb -C {{ ckb_data_dir }} replay --tmp-target='/tmp' --profile >> {{ ckb_data_dir }}/logs/run.log"
          environment:
            CKB_LOG: error
        - name: Start CKB
          become: true
          service:
            name: "{{ ckb_service }}"
            state: started
        - name: Get TPS
          shell: "grep 'End profiling, duration:.*s txs.* tps [0-9]+' {{ ckb_data_dir }}/logs/run.log | awk '{print $8}'"
          register: ckb_replay_tps
        - debug:
            msg: "{{ ckb_replay_tps.stdout }}"
      tags:
        - ckb_replay

    - name: Report In Brief
      block:
        - name: RPC local_node_info
          uri:
            method: post
            url: "http://{{ ansible_host }}:{{ ckb_rpc_listen_address.split(':')[1] }}"
            body_format: json
            headers:
              content-type: application/json
            body: '{"id": 0, "jsonrpc": "2.0", "method": "local_node_info", "params": []}'
          register: rpc_local_node_info
        - name: RPC get_consensus
          uri:
            method: post
            url: "http://{{ ansible_host }}:{{ ckb_rpc_listen_address.split(':')[1] }}"
            body_format: json
            body: '{"id": 0, "jsonrpc": "2.0", "method": "get_consensus", "params": []}'
          register: rpc_get_consensus
        - name: RPC get_tip_block_number
          uri:
            method: post
            url: "http://{{ ansible_host }}:{{ ckb_rpc_listen_address.split(':')[1] }}"
            body_format: json
            body: '{"id": 0, "jsonrpc": "2.0", "method": "get_tip_block_number", "params": []}'
          register: rpc_get_tip_block_number
        - name: Get node's start time
          shell: "head -n 1 {{ ckb_data_dir }}/logs/run.log" # | date '+%s' -d '${$1:0:30}')"
          register: node_start_time
        - name: Get node's current time
          shell: "grep -m 1 'block: {{ ckb_sync_target_number }},' {{ ckb_data_dir }}/logs/run.log"
          register: node_current_time
        - name: ckb replay tps
          shell: "grep 'End profiling, duration:.*s txs.* tps [0-9]+' {{ ckb_data_dir }}/logs/run.log | awk '{print $8}'"
          register: ckb_replay_tps
        - name: Append Entry To Report File
          delegate_to: localhost
          vars:
            network: "{{ rpc_get_consensus.json.result.id }}"
            tip: "{{ ckb_sync_target_number }}"
            version: "{{ rpc_local_node_info.json.result.version }}"
            time: "{{ node_current_time.stdout[0:19] | to_datetime - node_start_time.stdout[0:19] | to_datetime }}"
            speed: "{{ tip | float / (node_current_time.stdout[0:19] | to_datetime - node_start_time.stdout[0:19] | to_datetime).total_seconds() }}"
            replay_tps: "{{ ckb_replay_tps.stdout }}"
            entry: "| {{ version }} | {{ time }} | {{ speed | int }} | {{ tip }} | {{ inventory_hostname }} | {{ network }} | {{ replay_tps | int }} |"
          shell: "echo '{{ entry }}' > {{ inventory_hostname }}.brief.md"
      tags:
        - report_in_brief
        - wait_ckb_synchronization
