name: CKBIntegrationTest

on:
  workflow_call:
    inputs:
      CKB_GITHUB_REPOSITORY:
        required: true
        type: string
      CKB_GITHUB_SHA:
        required: true
        type: string

jobs:
  build-ckb:
    name: Build CKB
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ "ubuntu-latest", "macos-latest", "windows-latest" ]
      fail-fast: true
      max-parallel: 10
    defaults:
      run:
        working-directory: ckb-integration-test
    steps:
      - uses: actions/checkout@v2
        with:
          repository: nervosnetwork/ckb-integration-test
      - if: ${{ runner.os == 'Windows' }}
        run: |
          iex (New-Object System.Net.WebClient).DownloadString('https://get.scoop.sh')

          echo "$env:USERPROFILE\scoop\shims" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
          echo "${{ github.workspace }}\devtools\windows" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

          scoop install git
          scoop bucket add extras
          scoop install llvm yasm
      - name: Build CKB (${{ runner.os }}, ${{ matrix.os }}, ${{ inputs.CKB_GITHUB_REPOSITORY }}, ${{ inputs.CKB_GITHUB_SHA }})
        env:
          CKB_GITHUB_REPOSITORY: ${{ inputs.CKB_GITHUB_REPOSITORY }}
          CKB_GITHUB_SHA: ${{ inputs.CKB_GITHUB_SHA }}
        run: make build-ckb
      - uses: actions/upload-artifact@v2
        if: ${{ runner.os != 'Windows' }}
        with:
          name: Released CKB (${{ runner.os }}, ${{ matrix.os }})
          path: ckb-integration-test/repo/${{ inputs.CKB_GITHUB_REPOSITORY }}/target/release/ckb
          if-no-files-found: error
      - uses: actions/upload-artifact@v2
        if: ${{ runner.os == 'Windows' }}
        with:
          name: Released CKB (${{ runner.os }}, ${{ matrix.os }})
          path: ckb-integration-test/repo/${{ inputs.CKB_GITHUB_REPOSITORY }}/target/release/ckb.exe
          if-no-files-found: error

  build-ckb-integration-test:
    name: Build CKB-Integration-Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ "ubuntu-latest", "macos-latest", "windows-latest" ]
      fail-fast: true
      max-parallel: 10
    defaults:
      run:
        working-directory: ckb-integration-test
    steps:
      - uses: actions/checkout@v2
        with:
          repository: nervosnetwork/ckb-integration-test
      - if: ${{ runner.os == 'Windows' }}
        run: |
          iex (New-Object System.Net.WebClient).DownloadString('https://get.scoop.sh')

          echo "$env:USERPROFILE\scoop\shims" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
          echo "${{ github.workspace }}\devtools\windows" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

          scoop install git
          scoop bucket add extras
          scoop install llvm yasm
      - name: Build CKB-Integration-Test
        run: make build
      - uses: actions/upload-artifact@v2
        if: ${{ runner.os != 'Windows' }}
        with:
          name: Released CKB-Integration-Test (${{ runner.os }}, ${{ matrix.os }})
          path: ckb-integration-test/target/release/ckb-integration-test
          if-no-files-found: error
      - uses: actions/upload-artifact@v2
        if: ${{ runner.os == 'Windows' }}
        with:
          name: Released CKB-Integration-Test (${{ runner.os }}, ${{ matrix.os }})
          path: ckb-integration-test/target/release/ckb-integration-test.exe
          if-no-files-found: error

  run-test:
    name: Run Test Cases
    needs: [ build-ckb, build-ckb-integration-test ]
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ "ubuntu-latest", "macos-latest", "windows-latest" ]
      fail-fast: false
      max-parallel: 10
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v2
        with:
          repository: nervosnetwork/ckb-integration-test
      - uses: actions/download-artifact@v2
        with:
          name: Released CKB (${{ runner.os }}, ${{ matrix.os }})
          path: ckb-integration-test/testdata/bin
      - uses: actions/download-artifact@v2
        with:
          name: Released CKB-Integration-Test (${{ runner.os }}, ${{ matrix.os }})
          path: ckb-integration-test/testdata/bin
      - if: ${{ runner.os != 'Windows' }}
        run: |
          cd ./ckb-integration-test
          chmod +x ./testdata/bin/*
          ./testdata/bin/ckb-integration-test run \
            --ckb2021 testdata/bin/ckb
      ## TODO: testdata/db/ is only for Linux and macOS
      # - if: ${{ runner.os == 'Windows' }}
      #   run: |
      #     cd ./ckb-integration-test
      #     chmod +x ./testdata/bin/*
      #     ./testdata/bin/ckb-integration-test.exe run \
      #       --ckb2021 testdata/bin/ckb.exe
